sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: Ml651AYBEy8VLJQ4cyOty/5fFMho5+qQnYL86Fu0TLeduY9XHWN9u6Ge5Dl1fwcnIj8VZBqwf1PtcvWBwy7abd1DUoiJvJZQpPnrzem2ITu2Z7yec7uEZWk5Py6aJCtCs70Hv+58jC/aEfJraZPvSXll6rv/2knX2UX+tJYAguOIQxkdKt2gOdYdW8IeT/6DVNOwA3nlVYC47i9jN5a2JwR3g5pE0dt8J+0MMIjSxggirRQdx8CHvsl/xV+u3QuHhmwAHuiqtvy7ZQ/Ah4dHOq0auqNMFbl1bgb+uf0Lg6D2kIxKOpDyB+zgv5kMccnRRx5Kfl2FE+BuNvrwF92OHMRFa6qvfzi2yVGNqOyuCjhvItTkI0keUWIxc9ZV32BLHFC8k7BEOJje0vENKkOqZqSaE7ExKW+cOhBF3FuO6OSBoXqvIvuRYQdpUB/lZSr4XJI/sEufnz9WQYT61CFnEoMWiq75hr3gPJl4f4btPoMvf5xhJmM2T+qLjkstnKK+jYdCvjI05uTCTMaUqFf/4uLb/FG0U9w/654CaL1HXm8Rt5Si7RX/uD7ZsAvfYM20rsG34sh55a+2bwcXMzUvD+5CoK0VrPm2H35LCgoHemBlfv191evKrJs0711xaIAgvrNuzrfhr3d+puSwf93oUleJyb5pUbZMiUZieids7ZY=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: C/Bf1283ChCXi07DhfGCJMyFMgM2rVy4cEMLSG26OsyWSnotEahmWBklWbvh24u/vAwdGrmMiCLIK2K198vfN+0+/ZtvsFK8wImI7uMDP+0ZDHbc/rF/pKomVPaI2yiNrXv4wx2ielrGL6UYBo+sfNUSBT8FVxH7IiS0xGUA121T3Uv1Vxzg5cEQfjx9uydkdtv6MiE8JCVkpgJjC8WRTVMmCRStPA+hItS7/AwH3yg9fMpoWXJtixL6NNZe0Vpd4jWRtmgJT9k6X+Ny2T4NE3bRU9ztBKRhpZ1erD7LQPG4WQ5xWaNh1k9F/2Fj4MyzolhAbRxu4MXZ5niCj0YAsObfWBlsFhTwFkvKDNFGe9mxWXWWIEtM+uh59yb3GwLJoE9IPX1eGHo0CtykoyHafYLpA6CWZB9f92dhFPWOVTxDGq8KPHfxzthK/jwb3eiIkmIut54A/BceLraDZBb0fAAuLfswvhgCGIc5AZl0eab/cajgKh3dICouv/80jQzUqkUBGNzp2784Sc/fhIqxBmjncYyuLVw3s0U+RixtkcYe+O0WOKFK7mi2YhxGc7NzFqqNp10Pn+hwi5JiR2lZ+lNED2WarVGznhJ1e7NYX2Pzb+LWSkaxm3sZclj98f6ITooyZ3VUeYOWQNiMWR9mz86n47lHJ0S/i2G1HM8JFKQ=
